In [35]:
import pandas as pd

# Load dataset
data = pd.read_csv('../data/raw/reviews.csv')

# Show first rows
data.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [36]:
import pandas as pd

# Load dataset
data = pd.read_csv('../data/raw/reviews.csv')

# Show first 5 rows
data.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [37]:
print(data.columns)

Index(['Unnamed: 0.1', 'Unnamed: 0', 'asin', 'helpful', 'rating', 'reviewText',
       'reviewTime', 'reviewerID', 'reviewerName', 'summary',
       'unixReviewTime'],
      dtype='object')

In [38]:
data = data[['reviewText', 'rating']]

In [39]:
# create label
data['label'] = data['rating'].apply(lambda x: 1 if x <= 2 else 0)

In [40]:
data = data[data['rating'] != 3]

In [41]:
data = data[['reviewText','label']]
data.columns = ['reviewText', 'label']

In [42]:
data.head()

                                          reviewText  label
1  Great short read.  I didn't want to put it dow...      0
4  I did not expect this type of book to be in li...      0
5  Aislinn is a little girl with big dreams. Afte...      0
6  This has the makings of a good story... unfort...      1
7  I got this because I like collaborated short s...      0

In [43]:
data = data.dropna()    
data = data.drop_duplicates()

In [44]:
data['label'].value_counts()

label
0    6000
1    4000
Name: count, dtype: int64

In [45]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [46]:
import re
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

In [47]:
def clean_text(text):
    text = text.lower()  # lowercase
    text = re.sub(r'[^a-zA-Z]', ' ', text)  # remove numbers & symbols
    words = text.split()
    words = [w for w in words if w not in stop_words]  # remove stopwords
    return " ".join(words)

In [48]:
data['review'] = data['review'].apply(clean_text)

KeyError: 'review'

In [ ]:
print(data.columns)

Index(['reviewText', 'label'], dtype='object')

In [ ]:
data = data.rename(columns={'reviewText': 'review'})

In [ ]:
print(data.columns)

Index(['review', 'label'], dtype='object')

In [ ]:
data['review'] = data['review'].apply(clean_text)

In [ ]:
data.head()

                                              review  label
1  great short read want put read one sitting sex...      0
4  expect type book library pleased find price right      0
5  aislinn little girl big dreams death older bro...      0
6  makings good story unfortunately disappoints t...      1
7  got like collaborated short stories alot times...      0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer(max_features=5000)

In [ ]:
X = vectorizer.fit_transform(data['review'])
y = data['label']

In [ ]:
print(X.shape)

(10000, 5000)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8885

In [ ]:
import pickle

pickle.dump(model, open('../model/model.pkl', 'wb'))
pickle.dump(vectorizer, open('../model/vectorizer.pkl', 'wb'))

In [ ]:
import pickle

In [ ]:
pickle.dump(model, open('../model/model.pkl', 'wb'))

In [ ]:
pickle.dump(vectorizer, open('../model/vectorizer.pkl', 'wb'))

In [49]:
import pickle

with open('../model/model.pkl', 'wb') as f:
    pickle.dump(model, f)

with open('../model/vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

print("Saved successfully ✅")

Saved successfully ✅

In [50]:
from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(X_train, y_train)

LinearSVC()

In [51]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [52]:
import pickle

pickle.dump(model, open('../model/model.pkl', 'wb'))
pickle.dump(vectorizer, open('../model/vectorizer.pkl', 'wb'))

In [53]:
pip install textblob

Collecting textblob
  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: nltk>=3.9 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from textblob) (3.9.3)
Requirement already satisfied: click in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from nltk>=3.9->textblob) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from nltk>=3.9->textblob) (4.67.3)
Requirement already satisfied: colorama in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.19.0-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
    --------------------------------------- 10.2/624.3 kB ? eta -:--:--
    --------------------------------------- 10.2/624.3 kB ? eta -:--:--
   - ------------------------------------- 20.5/624.3 kB 131.3 kB/s eta 0:00:05
   -- ------------------------------------ 41.0/624.3 kB 196.9 kB/s eta 0:00:03
   --- ----------------------------------- 61.4/624.3 kB 252.2 kB/s eta 0:00:03
   ------ ------------------------------- 112.6/624.3 kB 409.6 kB/s eta 0:00:02
   -------------- ----------------------- 235.5/624.3 kB 722.1 kB/s eta 0:00:01
   ------------------------ --------------- 389.1/624.3 kB 1.1 MB/s eta 0:00:01
   ---------------------------------------  614.4/624.3 kB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 624.3/624.3 kB 1.5 MB/s eta 0:00:00
Installing collected packages: textblob
Successfully installed textblob-0.19.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [54]:
from textblob import TextBlob

def get_sentiment(text):
    return TextBlob(text).sentiment.polarity

data['sentiment'] = data['review'].apply(get_sentiment)

KeyError: 'review'

In [55]:
print(data.columns)

Index(['reviewText', 'label'], dtype='object')

In [56]:
data = data.rename(columns={'reviewText': 'review'})

In [57]:
from textblob import TextBlob

def get_sentiment(text):
    return TextBlob(text).sentiment.polarity

data['sentiment'] = data['review'].apply(get_sentiment)